spring.application.name=PASIR_Galusza_Pawel

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/galusza_pawel_k01_spring?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=user-gp
spring.datasource.password=strongUserPass123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# GraphQL Configuration
spring.graphql.http.path=/graphql
spring.graphql.schema.file-extensions=.graphql,.graphqls,.gqls

app.jwt.secret=${JWT_SECRET}